const EErrors = {
    ROUTING_ERROR: 1,
    INVALID_TYPES_ERROR: 2,
    DATABASE_ERROR: 3,
    AUTHENTICATION_ERROR: 4,
    VALIDATION_ERROR: 5,
    NOT_FOUND_ERROR: 6,
    FILE_UPLOAD_ERROR: 7,
    EXTERNAL_API_ERROR: 8

}

export default EErrors